# Build and deploy to github pages

name: Build and Deploy

on:
  push:
    branches: [ master ] # build master branch only

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
      with:
          persist-credentials: false # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.

    - name: Install and Build 🔧
      run: |
          npm ci
          npm run build
          
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
